const fs = require("fs");
const path = require("path");

/**
 * Copies the ABIs the web app needs out of the Hardhat artifacts, so the frontend
 * never hand-maintains a signature. Run after `hardhat compile`.
 */
const EXPORTS = {
  RhoFactory: "contracts/core/RhoFactory.sol/RhoFactory.json",
  RhoPair: "contracts/core/RhoPair.sol/RhoPair.json",
  RhoRouter: "contracts/periphery/RhoRouter.sol/RhoRouter.json",
  RhoLens: "contracts/periphery/RhoLens.sol/RhoLens.json",
  TestToken: "contracts/mocks/TestToken.sol/TestToken.json",
};

const artifactsDir = path.join(__dirname, "..", "artifacts");
const outDir = path.join(__dirname, "..", "..", "web", "src", "abi");
fs.mkdirSync(outDir, { recursive: true });

const lines = ["// Generated by contracts/scripts/export-abi.js - do not edit by hand.", ""];

for (const [name, relative] of Object.entries(EXPORTS)) {
  const file = path.join(artifactsDir, relative);
  if (!fs.existsSync(file)) throw new Error(`Missing artifact ${relative}. Run "npm run build" first.`);
  const { abi } = JSON.parse(fs.readFileSync(file, "utf8"));
  const constName = `${name.replace(/^Rho/, "").toLowerCase()}Abi`;
  lines.push(`export const ${constName} = ${JSON.stringify(abi, null, 2)} as const;`, "");
}

// Minimal ERC20 surface used for balances, allowances and approvals.
const view = (name, inputs, outputs) => ({
  type: "function",
  name,
  stateMutability: "view",
  inputs,
  outputs,
});
const addr = (name) => ({ name, type: "address" });
const u256 = (name = "") => ({ name, type: "uint256" });

const erc20Abi = [
  view("name", [], [{ name: "", type: "string" }]),
  view("symbol", [], [{ name: "", type: "string" }]),
  view("decimals", [], [{ name: "", type: "uint8" }]),
  view("totalSupply", [], [u256()]),
  view("balanceOf", [addr("owner")], [u256()]),
  view("allowance", [addr("owner"), addr("spender")], [u256()]),
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [addr("spender"), u256("value")],
    outputs: [{ name: "", type: "bool" }],
  },
];
lines.push(`export const erc20Abi = ${JSON.stringify(erc20Abi, null, 2)} as const;`, "");

const outFile = path.join(outDir, "index.ts");
fs.writeFileSync(outFile, lines.join("\n"));
console.log(`Wrote ${outFile}`);
